buffalo: add go.mod for use with vgo
First, establish baseline buffalo behavior, by using
"dep ensure" and then running tests:

	$ rm -rf /tmp/gopath
	$ mkdir /tmp/gopath
	$ export GOPATH=/tmp/gopath
	$ cd /tmp/gopath
	$ go get github.com/gobuffalo/buffalo
	$ cd src/github.com/gobuffalo/buffalo
	$ dep ensure
	$ go test ./...
	ok  	github.com/gobuffalo/buffalo	0.235s
	ok  	github.com/gobuffalo/buffalo/binding	0.174s
	?   	github.com/gobuffalo/buffalo/buffalo	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/build	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/destroy	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/generate	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/updater	[no test files]
	ok  	github.com/gobuffalo/buffalo/generators	0.137s
	ok  	github.com/gobuffalo/buffalo/generators/action	0.163s [no tests to run]
	?   	github.com/gobuffalo/buffalo/generators/assets	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/assets/standard	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/assets/webpack	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/docker	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/grift	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/mail	[no test files]
	ok  	github.com/gobuffalo/buffalo/generators/newapp	0.152s
	?   	github.com/gobuffalo/buffalo/generators/refresh	[no test files]
	ok  	github.com/gobuffalo/buffalo/generators/resource	0.134s
	?   	github.com/gobuffalo/buffalo/generators/soda	[no test files]
	?   	github.com/gobuffalo/buffalo/grifts	[no test files]
	ok  	github.com/gobuffalo/buffalo/mail	0.165s
	?   	github.com/gobuffalo/buffalo/meta	[no test files]
	--- FAIL: Test_PopTransaction (0.00s)
	        Error Trace:    pop_transaction_test.go:94
		Error:      	Received unexpected error:
		            	sqlite3 was not compiled into the binary
	        ...
	--- FAIL: Test_PopTransaction_Error (0.00s)
	        Error Trace:    pop_transaction_test.go:107
		Error:      	Received unexpected error:
		            	sqlite3 was not compiled into the binary
	        ...
	--- FAIL: Test_PopTransaction_NonSuccess (0.00s)
	        Error Trace:    pop_transaction_test.go:120
		Error:      	Received unexpected error:
		            	sqlite3 was not compiled into the binary
	        ...
	FAIL	github.com/gobuffalo/buffalo/middleware	0.170s
	ok  	github.com/gobuffalo/buffalo/middleware/basicauth	0.169s
	ok  	github.com/gobuffalo/buffalo/middleware/csrf	0.167s
	ok  	github.com/gobuffalo/buffalo/middleware/i18n	0.150s
	?   	github.com/gobuffalo/buffalo/middleware/ssl	[no test files]
	ok  	github.com/gobuffalo/buffalo/middleware/tokenauth	0.153s
	?   	github.com/gobuffalo/buffalo/plugins	[no test files]
	ok  	github.com/gobuffalo/buffalo/render	0.127s
	ok  	github.com/gobuffalo/buffalo/worker	0.100s
	$

Now use "vgo build" (or any other vgo command) to turn dep's Gopkg.lock
into a populated go.mod file:

	$ vgo build
	vgo: finding gopkg.in/yaml.v2 v2.2.1
	vgo: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
	vgo: finding gopkg.in/mail.v2 v2.0.0-20180301192024-63235f23494b
	vgo: finding gopkg.in/alexcesaro/quotedprintable.v3 v3.0.0-20150716171945-2caba252f4dc
	vgo: finding golang.org/x/sys v0.0.0-20180524104336-56ad15cc2170
	vgo: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
	vgo: finding golang.org/x/net v0.0.0-20180522190444-9ef9f5bb98a1
	...
	$ cat go.mod
	module github.com/gobuffalo/buffalo

	require (
		dmitri.shuralyov.com/text/kebabcase v0.0.0-20180217051803-40e40b42552a
		github.com/ajg/form v0.0.0-20160802194845-cc2954064ec9
		github.com/dgrijalva/jwt-go v0.0.0-20180308231308-06ea1031745c
		github.com/dustin/go-humanize v0.0.0-20180421182945-02af3965c54e
		github.com/fatih/color v1.7.0
		github.com/fsnotify/fsnotify v1.4.7
		github.com/gobuffalo/packr v1.11.0
		...
	)
	$

Run tests to see that baseline behavior hasn't changed:

	$ vgo test ./...
	ok  	github.com/gobuffalo/buffalo	0.251s
	ok  	github.com/gobuffalo/buffalo/binding	0.180s
	?   	github.com/gobuffalo/buffalo/buffalo	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/build	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/destroy	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/generate	[no test files]
	?   	github.com/gobuffalo/buffalo/buffalo/cmd/updater	[no test files]
	ok  	github.com/gobuffalo/buffalo/generators	0.140s
	ok  	github.com/gobuffalo/buffalo/generators/action	0.123s [no tests to run]
	?   	github.com/gobuffalo/buffalo/generators/assets	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/assets/standard	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/assets/webpack	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/docker	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/grift	[no test files]
	?   	github.com/gobuffalo/buffalo/generators/mail	[no test files]
	ok  	github.com/gobuffalo/buffalo/generators/newapp	0.149s
	?   	github.com/gobuffalo/buffalo/generators/refresh	[no test files]
	ok  	github.com/gobuffalo/buffalo/generators/resource	0.135s
	?   	github.com/gobuffalo/buffalo/generators/soda	[no test files]
	?   	github.com/gobuffalo/buffalo/grifts	[no test files]
	ok  	github.com/gobuffalo/buffalo/mail	0.157s
	?   	github.com/gobuffalo/buffalo/meta	[no test files]
	--- FAIL: Test_PopTransaction (0.00s)
	        Error Trace:    pop_transaction_test.go:94
		Error:      	Received unexpected error:
		            	sqlite3 was not compiled into the binary
	        ...
	--- FAIL: Test_PopTransaction_Error (0.00s)
	        Error Trace:    pop_transaction_test.go:107
		Error:      	Received unexpected error:
		            	sqlite3 was not compiled into the binary
	        ...
	--- FAIL: Test_PopTransaction_NonSuccess (0.00s)
	        Error Trace:    pop_transaction_test.go:120
		Error:      	Received unexpected error:
		            	sqlite3 was not compiled into the binary
	        ...
	FAIL	github.com/gobuffalo/buffalo/middleware	0.159s
	ok  	github.com/gobuffalo/buffalo/middleware/basicauth	0.157s
	ok  	github.com/gobuffalo/buffalo/middleware/csrf	0.166s
	ok  	github.com/gobuffalo/buffalo/middleware/i18n	0.171s
	?   	github.com/gobuffalo/buffalo/middleware/ssl	[no test files]
	ok  	github.com/gobuffalo/buffalo/middleware/tokenauth	0.173s
	?   	github.com/gobuffalo/buffalo/plugins	[no test files]
	ok  	github.com/gobuffalo/buffalo/render	0.128s
	ok  	github.com/gobuffalo/buffalo/worker	0.079s
	$

Finally, git add go.mod and git commit.